### ISSUE TITLE
Archi

### ISSUE THREAD

**Issue by sithumonline** [sliit-foss/student-sorter#1]
![student-sorter](https://user-images.githubusercontent.com/24352487/133944989-1a44a6d0-2f79-4313-a979-64192e8bd58b.png)

https://www.fastify.io/docs/latest/Getting-Started/
https://www.prisma.io/docs/concepts/database-connectors/postgresql
https://www.prisma.io/fastify
https://hub.docker.com/_/postgres

```yaml
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: oceanx
      POSTGRES_USER: rox

  adminer:
    image: adminer
    #restart: 
    ports:
      - 8088:8080
```
